spring:
  application:
    name: finflow-wallet

  datasource:
    url: jdbc:mysql://localhost:3306/finflow
    username: finflow_user
    password: finflow123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: l+j9pS+OKspW+/C/s9tWt3NHCNMdwCTLRHHsyFzT+I0=
  expiration-ms: 3600000

resilience4j:
  circuitbreaker:
    instances:
      exchangeRate:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
